name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a test
        run: echo "j;kjdfsngkbjlSKJHITRNLGKBGu 9pq560]Q3
        - OITJ5YIOW HUJIUEW'T9YH SUGHG SFUHIGIGUITURIHGFGHGSHKFGKFJGHJG HJTIG OI GH
        
        
        Test are passed. Gleb is a good man. LOL"
gyu1fynkb bvjkktrhj
